DEFAULT_SPECTROGRAM_FREQ_SPACING = 50
MAX_TERMINAL_COLORS = 256

DEFAULT_SPECTROGRAM_SAMPLE_RATE = 1000
DEFAULT_CMAP = "greys"
DEFAULT_CHAR_MAP = "quarter"
SPECTROGRAM_LOWER_QUANTILE = 0.01
SPECTROGRAM_UPPER_QUANTILE = 0.99
DEFAULT_SPECTROGRAM_MIN_FREQ = 100
DEFAULT_SPECTROGRAM_MAX_FREQ = 8000

GUI_DEFAULT_MAX_DURATION = 6
GUI_MAX_IDX_LEN = 3

MIN_TIMESCALE = 0.01
MAX_TIMESCALE = 10.0
DEFAULT_TIME_STEP_FRAC = 0.25

MAX_CURSES_WINDOWS = 200
TERM_CHAR_ASPECT_RATIO = 2.5  # Ratio of height to width of a typical terminal character
